#!/usr/bin/env bash
# 1hour.guide 自动内容生产 - cron 入口
#
# 工作流：
#   1) 读取 topics.yaml 第一个 status:pending 项
#   2) 调用 distro 生成教程
#   3) 把 status 改为 published
#   4) commit topics.yaml + tutorials/<slug>/
#   5) publish.sh 推送 → CF 自动部署
#
# 用法：
#   ./auto-publish-next.sh          # 真跑
#   DRY_RUN=true ./auto-publish-next.sh  # 演练，不真改

set -euo pipefail

SITE_DIR="/Users/zoe/projects/labs.zoe.im/1hour-guide"
CONTENT_DIR="/Users/zoe/projects/labs.zoe.im/1hour-guide-content"
TOPICS="$SITE_DIR/topics.yaml"
GEN="/Users/zoe/projects/labs.zoe.im/distro/scripts/gen-1hour-tutorial.sh"
PUBLISH="$SITE_DIR/publish.sh"

DRY_RUN="${DRY_RUN:-false}"

if [ ! -f "$TOPICS" ]; then
  echo "❌ topics.yaml 不存在: $TOPICS"
  exit 1
fi

# 用 python 解析 yaml 找出第一个 pending 的 item
ITEM_JSON=$(python3 - <<PY
import yaml, json, sys
with open("$TOPICS") as f:
    data = yaml.safe_load(f)
for i, item in enumerate(data.get("queue", [])):
    if item.get("status") == "pending":
        item["_index"] = i
        print(json.dumps(item, ensure_ascii=False))
        sys.exit(0)
sys.exit(1)
PY
) || {
  echo "ℹ️  topics.yaml 中没有 pending 项，退出"
  exit 0
}

SLUG=$(echo "$ITEM_JSON" | jq -r .slug)
CATEGORY=$(echo "$ITEM_JSON" | jq -r .category)
TOPIC=$(echo "$ITEM_JSON" | jq -r .topic)
TAGS=$(echo "$ITEM_JSON" | jq -r '.tags // ""')
REF=$(echo "$ITEM_JSON" | jq -r '.reference // ""')
NEXT_STEP=$(echo "$ITEM_JSON" | jq -r '.next_step // ""')
DIFF=$(echo "$ITEM_JSON" | jq -r '.difficulty // "beginner"')
AUDIENCE_VAL=$(echo "$ITEM_JSON" | jq -r '.audience // ""')
PAIN_VAL=$(echo "$ITEM_JSON" | jq -r '.pain_point // ""')
INDEX=$(echo "$ITEM_JSON" | jq -r '._index')

echo "▶ 下一个: $SLUG ($CATEGORY)"
echo "   topic: $TOPIC"
[ -n "$AUDIENCE_VAL" ] && echo "   audience: $AUDIENCE_VAL"
[ -n "$PAIN_VAL" ]     && echo "   pain: $PAIN_VAL"

if [ "$DRY_RUN" = "true" ]; then
  echo "[DRY_RUN] 跳过实际生成"
  exit 0
fi

# 1) 生成教程
DIFFICULTY="$DIFF" AUDIENCE="$AUDIENCE_VAL" PAIN_POINT="$PAIN_VAL" \
  "$GEN" "$SLUG" "$CATEGORY" "$TOPIC" "$REF" "$NEXT_STEP" "$TAGS"

# 2) 把 topics.yaml 中该项 status 改为 published
python3 - <<PY
import yaml
with open("$TOPICS") as f:
    data = yaml.safe_load(f)
data["queue"][$INDEX]["status"] = "published"
with open("$TOPICS", "w") as f:
    yaml.safe_dump(data, f, allow_unicode=True, sort_keys=False, default_flow_style=False)
PY

# 3) 提交 topics.yaml 变更（在 site repo）
cd "$SITE_DIR"
if ! git diff --quiet -- topics.yaml; then
  git add topics.yaml
  git commit -m "chore(topics): mark $SLUG as published" || true
fi

# 4) publish.sh 双 push（content + site bump → 触发 CF 部署）
"$PUBLISH" "feat: add $SLUG tutorial (auto-generated by patrol)"

echo
echo "✅ 已自动发布 $SLUG"
echo "   将在 1-2 分钟后在 https://1hour.guide/zh/tutorials/$SLUG/ 上线"
